import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { Groceries } from '../../../components/templates';
import { useGroceriesContext } from '../../../hooks';
import { fetch } from '../../../util/api';
import { refreshAccessToken } from '../../../util/token';

type Props = {
    groceries: Grocery[];
}

export default function Grocery({ groceries }: Props) {
    const { updateGroceries } = useGroceriesContext();

    useEffect(() => {
        updateGroceries(groceries);
        // eslint-disable-next-line
    }, []);

    return (
        <>
            <Head>
                <title>Smapp | Smart Meal Plan App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Groceries />
        </>
    );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
    try {
        const { data: groceries } = await fetch.get<Grocery[]>(`${process.env.NEXT_PUBLIC_SERVER_URL || 'http://localhost:4500'}/groceries`, {
            withCredentials: true,
            headers: {
                Cookie: context.req.headers.cookie
            }
        });
        return { props: { groceries } };
    } catch (error) {
        return {
            redirect: {
                destination: '/login'
            }
        };
    }
}