import Head from 'next/head';
import { useRouter } from 'next/router';
import { Button } from '../components';

export default function Home() {
    const router = useRouter();
    return (
        <>
            <Head>
                <title>Smapp | Smart Meal Plan App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Button label='Create Account' onClick={() => router.push('/user/new')} />
            <Button label='Login' onClick={() => router.push('/login')} />
        </>
    );
}