import Head from 'next/head';
import { useRouter } from 'next/router';
import { Button, Container } from '../components';
import { StartPage } from '../components/templates';

export default function Home() {
    return (
        <>
            <Head>
                <title>Smapp | Smart Meal Plan App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <StartPage />
            <Container>
                <h1>
                    Smapp
                </h1>
            </Container>
        </>
    );
}