import Head from 'next/head';
import { LandingPage } from '../components/templates';

export default function Home() {
    return (
        <>
            <Head>
                <title>Smapp | Smart Meal Plan App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <LandingPage />
        </>
    );
}