import Head from 'next/head';
import styles from '../styles/Home.module.css'
import { List, ListItem, Main } from '../components';

type Props = {}
export default function shoppingList({ }: Props) {
    return (
        <>
            <Head>
                <title>Shopping List</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <List>
                    <ListItem>Test</ListItem>
                    <ListItem>Test2</ListItem>
                </List>
            </Main>
        </>
    );
}