import Head from 'next/head';
import { useRouter } from 'next/router';
import { Button, Container, Icon } from '../../../../components';
import { RecipeEditor } from '../../../../components/templates';

export default function PostPage() {
    const router = useRouter();

    return (
        <>
            <Head>
                <title>Smapp | Smart Meal Plan App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Container>
                <Button
                    variant='ghost'
                    onClick={() => router.push('/user/recipes')}>
                    <Icon name='chevronLeft' />Back
                </Button>
                <RecipeEditor />
            </Container>
        </>
    );
}