import Head from 'next/head';
import { ChangeEvent, useReducer } from 'react';
import { Button, Icon, List, Main } from '../../elements';
import GroceryItem from './blocks/GroceryItem';
import GroceryList from './blocks/GroceryList';

const mockGroceries: Grocery[] = [
    {
        id: '1',
        name: 'tomatoes',
        updated_at: new Date(1672774937044),
        amount: 1,
        item_id: '1',
        isChecked: false
    }, {
        id: '3',
        name: 'onions',
        updated_at: new Date(1672774937044),
        amount: 5,
        item_id: '2',
        isChecked: false
    }
];

type ActionType = 'check';
interface Action extends Pick<Grocery, 'id'> {
    type: ActionType;
    checked?: boolean;
}

function reducer(state: Grocery[], action: Action): Array<Grocery> {
    const { type, id } = action;

    if (type === 'check') {
        const { checked } = action;
        if (typeof checked === 'undefined') {
            throw new Error('Missing required property.');
        }

        return state.map(item => {
            if (item.id === id) {
                item.isChecked = checked;
            }
            return item;
        });

    }
    return state;
}

export default function ShoppingList() {
    const [state, dispatch] = useReducer(reducer, mockGroceries);

    function toggleCheckbox(event: ChangeEvent<HTMLInputElement>, id: string) {
        const checked = event.target.checked;
        dispatch({
            id,
            type: 'check',
            checked,
        });
    }

    return (
        <>
            <Head>
                <title>Shopping List</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <Button label='Generate' />
                <GroceryList state={state} toggleCheckbox={toggleCheckbox} />
                <Button
                    variant='ghost'
                    onClick={() => console.log('clicked')}>
                    <Icon name='plus' />
                    Add an Item
                </Button>
                <GroceryList state={state} toggleCheckbox={toggleCheckbox} crossed />
            </Main>
        </>
    );
}