import Head from 'next/head';
import { useState } from 'react';
import { useGroceriesContext } from '../../../hooks';

import { Button, Icon } from '../../elements';
import GroceryInput from './blocks/GroceryInput';
import GroceryList from './blocks/GroceryList';
import GroupedButtons from './blocks/GroupedButtons';

export default function ShoppingList() {
    const [isEditing, setIsEditing] = useState<boolean>(false);
    const { groceries } = useGroceriesContext();

    function toggleInput(): void {
        setIsEditing(prev => !prev);
    }

    return (
        <>
            <Head>
                <title>Shopping List</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <GroupedButtons />
            <GroceryList groceryList={groceries.filter(item => !item.isChecked)} />
            {/*  {isEditing && <GroceryInput toggle={toggleInput} />} */}
            <Button
                variant='ghost'
                onClick={() => setIsEditing(true)}>
                <Icon name='plus' />
                Add an Item
            </Button>
            <GroceryList
                groceryList={groceries.filter(item => item.isChecked)}
                isCheckedList />
        </>
    );
}