import Head from 'next/head';
import { Container } from '../../elements';
import { GroceryList, GroupedButtons } from './blocks';

export default function Groceries() {
    return (
        <>
            <Head>
                <title>Smapp - Grocery List</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Container>
                <GroupedButtons />
                <GroceryList />
            </Container>
        </>
    );
}