import Head from 'next/head';
import { useGroceriesContext } from '../../../hooks';

import { GroceryList, GroupedButtons } from './blocks';

export default function Groceries() {
    const { groceries } = useGroceriesContext();

    return (
        <>
            <Head>
                <title>Shopping List</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <GroupedButtons />
            <GroceryList groceryList={groceries.filter(item => !item.isChecked)} />
            <GroceryList
                groceryList={groceries.filter(item => item.isChecked)}
                isCheckedList />
        </>
    );
}